### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ccorcos** [keijiro/VideoLabTest#1]
Where are the GLSL shaders for all these visuals?

**Comment by keijiro** [comment]
Unity uses HLSL instead of GLSL. See `.shader` files, like [this](https://github.com/keijiro/VideolabTest/blob/master/Assets/VideolabTest/Splash/Splash.shader).

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by ccorcos** [comment]
Interesting. I haven't used unity yet. I'll check that out. Is HLSL still proprietary?

**Comment by keijiro** [comment]
I'm not sure if it has been proprietary, but it's opened in several ways https://github.com/Microsoft/DirectXShaderCompiler
