### ISSUE TITLE
Videolab 1.1 with OP-Z 1.1

### ISSUE THREAD

**Issue by Animamusic** [keijiro/VideoLabTest#2]
Will you be releasing any any new videopaks compatible with the OP-Z 1.1 update?

**Comment by keijiro** [comment]
Yes. I just realised that it's released.

**Comment by Animamusic** [comment]
Awesome, looking forward to it! 

Would you mind notifying me when you post the updated videopaks? I love using the ones you make

**Comment by keijiro** [comment]
@Animamusic I just realized an updated version.

https://github.com/keijiro/VideolabTest/releases/tag/v0.1.6

I'm closing this issue now. Please feel free to reopen if you find any problem with it.
