### ISSUE TITLE
Textures and filesize

### ISSUE THREAD

**Issue by kybernaughty** [keijiro/VideoLabTest#4]
Sorry to bother you with this amateur question, but 
A.) is there a filesize limit for a videopak to run on ipad (6gen)
B.) i can‘t get terrain textures to work, the terrain features are just filled in magenta
Thanks!

**Comment by keijiro** [comment]
A) Although I'm not sure about the details of the iPad specs, I think it's capable of handling 1 or 2 GB apps without any issue.
B) I guess that there is a problem with terrain support. Could you report this problem to TE? https://github.com/teenageengineering/videolab

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
